---
title: 'Analysis 1: Overall descriptive results'
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE)
```

## Overview

This code provides an overall view of children's performance in the two tasks. 

## Load libraries
```{r}
library("here")
library("tidyverse")
library("afex")
library("lme4")
library("janitor")

setwd(here())
```
## Load data

Compute subject level data for N and More separately, and combined

```{r}
data_n_trial_level_raw = read.csv(here("Data/data_n_long.csv"), check.names = FALSE) 

data_n_trial_level = data_n_trial_level_raw %>%
  select(id, sex, ses, age_months, location, acc, completed_task, within_id, age_years_group) %>%
  mutate(task = "N")

data_more_trial_level_raw = read.csv(here("Data/data_more_long.csv"), check.names = FALSE) 

data_more_trial_level = data_more_trial_level_raw %>%
  select(id, sex, ses, age_months, location, acc, completed_task, within_id, age_years_group) %>%
  mutate(task = "More")

# Getting subj level data
data_n_subj_level = data_n_trial_level %>%
  group_by(id, age_months, sex, ses, location, task, completed_task, within_id, age_years_group) %>%
  summarise(acc_subj = mean(acc)) %>%
  mutate(sex = as.factor(sex),
         ses = as.factor(ses),
         id = as.factor(id),
         location = as.factor(location)) %>%
  data.frame()

data_more_subj_level = data_more_trial_level %>%
  group_by(id, age_months, sex, ses, location, task, completed_task, within_id, age_years_group) %>%
  summarise(acc_subj = mean(acc)) %>%
  mutate(sex = as.factor(sex),
         ses = as.factor(ses),
         id = as.factor(id),
         location = as.factor(location)) %>%
  data.frame()

# if doing combined data set
data_combined_subj_level = rbind(data_n_subj_level, data_more_subj_level)

```
## Demographic information
```{r}
# Number of participants, complicated ---------------------
# total number of completed, not total participants because some children received both tasks
total_completed_tasks = nrow(data_combined_subj_level)
total_completed_tasks

# total number of trials/observations
total_num_trials = nrow(data_n_trial_level) + nrow(data_more_trial_level)
total_num_trials

# number of children who received both tasks
data_within_data_subj_level = read.csv(here("Data/data_within_data.csv"), check.names = FALSE) %>%
  group_by(within_id, age_years_group, sex, age_months) %>%
  summarise(subj_acc = mean(acc)) %>%
  ungroup()

total_both_tasks = nrow(data_within_data_subj_level)
total_both_tasks

# number of children who only received one task
total_one_task = total_completed_tasks - nrow(data_within_data_subj_level) * 2
total_one_task

# total number of participants 
total_participants = total_both_tasks + total_one_task
total_participants

# Participants' demographic info ------------------
# identify children who only received one task
subj_one_task = data_combined_subj_level %>%
  filter(completed_task == 1) %>%
  select(within_id, age_months, sex, location, age_years_group)

subj_two_tasks = data_combined_subj_level %>%
  filter(completed_task == 2) %>%
  group_by(within_id, age_months, sex, location, age_years_group) %>%
  summarise(n = n()) %>%
  select(-n)

subj_all = rbind(subj_one_task, subj_two_tasks)

subj_all %>%
  summarise(mean = mean(age_months)/12, median = median(age_months)/12, min = min(age_months)/12, max = max(age_months)/12)

subj_all %>%
  tabyl(sex)

subj_all %>%
  tabyl(age_years_group)

subj_all %>%
  mutate(tested_in_school = ifelse(location == "Lab", "n", "y")) %>%
  tabyl(tested_in_school)
```
## model: acc_subj ~ age + sex + task + location
```{r}
# N task, without school factor
model = lm(acc_subj ~ age_months + sex, data = subset(data_combined_subj_level, task == "N"))
summary(model)
anova(model)

# More task, without school factor
model = lm(acc_subj ~ age_months + sex, data = subset(data_combined_subj_level, task == "More"))
summary(model)
anova(model)

# both tasks, for school tested subjects only
model = lm(acc_subj ~ age_months + sex + location, data = subset(data_combined_subj_level, location != "Lab"))
summary(model)
anova(model)
  
```

## Plots
```{r}
fontsize = 13

# scatter plot: Accuracy is linearly related to age, but no sex difference
ggplot(data = data_combined_subj_level, aes(x = age_months, y = acc_subj, color = sex)) +
  geom_point(cex = 0.8) +
  geom_smooth(data = subset(data_combined_subj_level, sex == "F"), method="lm", na.rm = F, size = 1, color = "lightcoral", fill = "lightcoral") +
  geom_smooth(data = subset(data_combined_subj_level, sex == "M"), method="lm", na.rm = F, size = 1, color = "cyan3", fill = "cyan3") +
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) +
  #ggtitle("The Which-N task") +
  ylab("Proportion of correct trials") + 
  xlab("Age (months)") +
  labs(color = "Sex") +
  theme(plot.title = element_text(size = fontsize, hjust = 0.5), text=element_text(size=fontsize)) +
  scale_color_manual(values = c("lightcoral", "cyan3","grey72"))

fig = here("Plots", "descriptive", "scatterplot_acc_by_age_gender.jpeg")
ggsave(fig, height = 4, width = 6, dpi = 300)

# box plot; the effect of school
ggplot(data_combined_subj_level, aes(x = reorder(location, acc_subj), y = acc_subj)) +
  geom_boxplot() +
  #geom_jitter() +
  #ylim(c(0,1.05)) +
  coord_flip() +
  ylab("Proportion of correct trials") +
  xlab("Schools") +
  geom_hline(yintercept=0.5, linetype="dashed", color = "lightcoral", size = 0.8) + 
  theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
                     panel.grid.minor = element_blank(), axis.line = element_line(colour = "black")) + 
  theme(plot.title = element_text(size = fontsize, hjust = 0.5), text=element_text(size=fontsize), legend.position = "none", axis.text.y = element_text(size = 0))
  
fig = here("Plots", "descriptive", "acc_by_school.jpeg")
ggsave(fig, height = 4, width = 4.5, dpi = 300)

# density plot: task difference plot, N develops earlier than more
ggplot(data_combined_subj_level, aes(x = acc_subj, fill = task)) +
  geom_density(aes(y = ..scaled..), adjust = 1.5, alpha = 0.4) +
  xlab("Accuracy") +
  ylab("Density") +
  scale_fill_discrete(name = "Task", labels = c("More", "N")) +
  theme_classic(base_size = 13)

fig = here("Plots", "descriptive", "acc_by_task.jpeg")
ggsave(fig, height = 4, width = 6, dpi = 300)
```
## The effect of some features (i.e., length_diff, transposition)
```{r}
# the More task
temp_more = data_more_trial_level_raw %>%
  filter(age_years_group > 2 & age_years_group < 7) %>%
  group_by(category, age_years_group, id) %>%
  summarise(subj_acc = mean(acc)) %>%
  group_by(category, age_years_group) %>%
  summarise(group_acc = mean(subj_acc), se_acc = sd(subj_acc)/sqrt(n()), n = n()) %>%
  ungroup() %>%
  mutate(age_years_group = factor(age_years_group),
         category = factor(category, levels = c("S", "M-DP", "M-SP-no-T", "M-SP-with-T"))) 

ggplot(temp_more, aes(x = age_years_group, y = group_acc, fill = category)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin=group_acc-se_acc, ymax=group_acc+se_acc), width=.2,
                 position=position_dodge(.9)) +
  theme_classic() +
  geom_hline(yintercept=0.5, linetype="dashed", color = "black", size=0.5)

fig = here("Plots", "descriptive", "acc_by_category_more.jpeg")
ggsave(fig, height = 4, width = 6, dpi = 300)

# the N task
temp_n = data_n_trial_level_raw %>%
  filter(age_years_group > 2 & age_years_group < 7) %>%
  group_by(category, age_years_group, id) %>%
  summarise(subj_acc = mean(acc)) %>%
  group_by(category, age_years_group) %>%
  summarise(group_acc = mean(subj_acc), se_acc = sd(subj_acc)/sqrt(n()), n = n()) %>%
  ungroup() %>%
  mutate(age_years_group = factor(age_years_group),
         category = factor(category, levels = c("S", "M-DP", "M-SP-no-T", "M-SP-with-T"))) 

ggplot(temp_n, aes(x = age_years_group, y = group_acc, fill = category)) +
  geom_bar(stat = "identity", position = position_dodge()) +
  geom_errorbar(aes(ymin=group_acc-se_acc, ymax=group_acc+se_acc), width=.2,
                 position=position_dodge(.9)) +
  theme_classic() +
  geom_hline(yintercept=0.5, linetype="dashed", color = "black", size=0.5)

fig = here("Plots", "descriptive", "acc_by_category_n.jpeg")
ggsave(fig, height = 4, width = 6, dpi = 300)
  
```